# Generated by Django 3.1 on 2025-05-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailschedule',
            old_name='scheduled_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='emailschedule',
            old_name='scheduled_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='emailschedule',
            name='interval',
        ),
        migrations.AddField(
            model_name='emailschedule',
            name='duration',
            field=models.CharField(default='1 day', max_length=100),
        ),
        migrations.AddField(
            model_name='emailschedule',
            name='receivers',
            field=models.JSONField(default=list),
        ),
    ]
