# Generated by Django 3.1.12 on 2025-05-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20250511_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailhistory',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='receiver',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='status',
            field=models.CharField(default='SENT', max_length=10),
        ),
    ]
