# Generated by Django 3.1.12 on 2025-05-13 09:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20250511_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailhistory',
            options={},
        ),
        migrations.RenameField(
            model_name='emailschedule',
            old_name='date',
            new_name='scheduled_date',
        ),
        migrations.RenameField(
            model_name='emailschedule',
            old_name='time',
            new_name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='emailhistory',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='emailhistory',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='emailschedule',
            name='duration',
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='recipient',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailtemplate'),
        ),
        migrations.AddField(
            model_name='emailschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emailschedule',
            name='interval',
            field=models.CharField(default='1 day', max_length=50),
        ),
        migrations.AddField(
            model_name='emailschedule',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='receivers',
            field=models.JSONField(),
        ),
    ]
