# Generated by Django 5.2.1 on 2025-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20250513_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailschedule',
            name='status',
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='recipient',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='interval',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='receivers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
